/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as arbitrum from "./arbitrum";
export type { arbitrum };
export type { GnosisAmb } from "./GnosisAmb";
export type { Multichain } from "./Multichain";
export type { OptimismAmb } from "./OptimismAmb";
