sources:
  - name: Connext_Kovan
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-v0-kovan
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: kovan_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Staging_Kovan
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-staging-kovan
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: stagingkovan_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Test_Kovan
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-test-kovan
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: testkovan_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Rinkeby
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-v0-rinkeby
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: rinkeby_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Staging_Rinkeby
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-staging-rinkeby
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: stagingrinkeby_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Test_Rinkeby
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-test-rinkeby
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: testrinkeby_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Goerli
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-v0-goerli
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: goerli_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Staging_Goerli
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-staging-goerli
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: staginggoerli_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Test_Goerli
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-test-goerli
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: testgoerli_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250

documents:
  - ./example-query.graphql
