sources:
  - name: Connext_Rinkeby
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-v0-rinkeby
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: rinkeby_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Goerli
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-v0-goerli
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: goerli_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Staging_Goerli
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-staging-goerli
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: staginggoerli_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Test_Goerli
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-test-goerli
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: testgoerli_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_OptimismGoerli
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/amarok-runtime-v0-opt-goerli
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: optimismgoerli_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Test_OptimismGoerli
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/runtime-v0-opt-goerli-test
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: testoptimismgoerli_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Staging_OptimismGoerli
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/runtime-v0-opt-goerli-staging
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: stagingoptimismgoerli_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Mumbai
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-v0-mumbai
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: mumbai_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Staging_Mumbai
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/connext/nxtp-amarok-runtime-staging-mumbai
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: stagingmumbai_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Local1337
    handler:
      graphql:
        endpoint: "{env.GRAPH_1337_ENDPOINT}"
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: local1337_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250
  - name: Connext_Local1338
    handler:
      graphql:
        endpoint: "{env.GRAPH_1338_ENDPOINT}"
        retry: 5
        timeout: 30000 # 30 seconds
    transforms:
      - prefix:
          value: local1338_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
      - autoPagination:
          validateSchema: true
          limitOfRecords: 250

documents:
  - ./example-query.graphql
