export const AutomationVaultAbi = [
  {
    inputs: [
      { internalType: "address", name: "_owner", type: "address" },
      { internalType: "address", name: "_nativeToken", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AutomationVault_ExecFailed", type: "error" },
  { inputs: [], name: "AutomationVault_NativeTokenTransferFailed", type: "error" },
  { inputs: [], name: "AutomationVault_NotApprovedJobSelector", type: "error" },
  { inputs: [], name: "AutomationVault_NotApprovedRelayCaller", type: "error" },
  { inputs: [], name: "AutomationVault_OnlyOwner", type: "error" },
  { inputs: [], name: "AutomationVault_OnlyPendingOwner", type: "error" },
  { inputs: [], name: "AutomationVault_RelayAlreadyApproved", type: "error" },
  { inputs: [], name: "AutomationVault_RelayZero", type: "error" },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "_owner", type: "address" }],
    name: "AcceptOwner",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "_job", type: "address" }],
    name: "ApproveJob",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "_job", type: "address" },
      { indexed: true, internalType: "bytes4", name: "_functionSelector", type: "bytes4" },
    ],
    name: "ApproveJobSelector",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "_relay", type: "address" }],
    name: "ApproveRelay",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "_relay", type: "address" },
      { indexed: true, internalType: "address", name: "_caller", type: "address" },
    ],
    name: "ApproveRelayCaller",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "_pendingOwner", type: "address" }],
    name: "ChangeOwner",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "_relay", type: "address" }],
    name: "DeleteRelay",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "_relay", type: "address" },
      { indexed: true, internalType: "address", name: "_relayCaller", type: "address" },
      { indexed: true, internalType: "address", name: "_feeRecipient", type: "address" },
      { indexed: false, internalType: "address", name: "_feeToken", type: "address" },
      { indexed: false, internalType: "uint256", name: "_fee", type: "uint256" },
    ],
    name: "IssuePayment",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "_relay", type: "address" },
      { indexed: true, internalType: "address", name: "_relayCaller", type: "address" },
      { indexed: true, internalType: "address", name: "_job", type: "address" },
      { indexed: false, internalType: "bytes", name: "_jobData", type: "bytes" },
    ],
    name: "JobExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "_sender", type: "address" },
      { indexed: false, internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "NativeTokenReceived",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "_token", type: "address" },
      { indexed: false, internalType: "uint256", name: "_amount", type: "uint256" },
      { indexed: true, internalType: "address", name: "_receiver", type: "address" },
    ],
    name: "WithdrawFunds",
    type: "event",
  },
  {
    inputs: [],
    name: "NATIVE_TOKEN",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "acceptOwner", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [
      { internalType: "address", name: "_relay", type: "address" },
      { internalType: "address[]", name: "_callers", type: "address[]" },
      {
        components: [
          { internalType: "address", name: "job", type: "address" },
          { internalType: "bytes4[]", name: "functionSelectors", type: "bytes4[]" },
        ],
        internalType: "struct IAutomationVault.JobData[]",
        name: "_jobsData",
        type: "tuple[]",
      },
    ],
    name: "addRelay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_pendingOwner", type: "address" }],
    name: "changeOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_relay", type: "address" }],
    name: "deleteRelay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_relayCaller", type: "address" },
      {
        components: [
          { internalType: "address", name: "job", type: "address" },
          { internalType: "bytes", name: "jobData", type: "bytes" },
        ],
        internalType: "struct IAutomationVault.ExecData[]",
        name: "_execData",
        type: "tuple[]",
      },
      {
        components: [
          { internalType: "address", name: "feeRecipient", type: "address" },
          { internalType: "address", name: "feeToken", type: "address" },
          { internalType: "uint256", name: "fee", type: "uint256" },
        ],
        internalType: "struct IAutomationVault.FeeData[]",
        name: "_feeData",
        type: "tuple[]",
      },
    ],
    name: "exec",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_relay", type: "address" }],
    name: "getRelayData",
    outputs: [
      { internalType: "address[]", name: "_callers", type: "address[]" },
      {
        components: [
          { internalType: "address", name: "job", type: "address" },
          { internalType: "bytes4[]", name: "functionSelectors", type: "bytes4[]" },
        ],
        internalType: "struct IAutomationVault.JobData[]",
        name: "_jobsData",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_relay", type: "address" },
      { internalType: "address[]", name: "_callers", type: "address[]" },
      {
        components: [
          { internalType: "address", name: "job", type: "address" },
          { internalType: "bytes4[]", name: "functionSelectors", type: "bytes4[]" },
        ],
        internalType: "struct IAutomationVault.JobData[]",
        name: "_jobsData",
        type: "tuple[]",
      },
    ],
    name: "modifyRelay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_relay", type: "address" },
      { internalType: "address[]", name: "_callers", type: "address[]" },
    ],
    name: "modifyRelayCallers",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_relay", type: "address" },
      {
        components: [
          { internalType: "address", name: "job", type: "address" },
          { internalType: "bytes4[]", name: "functionSelectors", type: "bytes4[]" },
        ],
        internalType: "struct IAutomationVault.JobData[]",
        name: "_jobsData",
        type: "tuple[]",
      },
    ],
    name: "modifyRelayJobs",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingOwner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "relays",
    outputs: [{ internalType: "address[]", name: "_relayList", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_token", type: "address" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "address", name: "_receiver", type: "address" },
    ],
    name: "withdrawFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
];
